### ISSUE TITLE
填写成功也会邮件提醒未知错误

### ISSUE THREAD

**Issue by diao597576613** [HPShark/xdu_chenwuwanjian#1]
根据作者源代码配置好环境以后，其他问题都没，就是每次都会收到邮件说遇到未知错误，但是点进去看晨午晚检都已经填写成功

**Comment by HPShark** [comment]
bug已修复~可以下载昨天更新后的代码试一下。是index.py里行面有个log函数，传入的text要进行str()，因为此时传入的upload_message的信息是json格式的。

**Comment by HPShark** [comment]
还有就是老版本的代码提交完之后你去晨午检看结果定位那里应该是白的，因为post的时候没有提交upload_message信息（在Utils.py的91行）....新代码也已经修复了，建议重新下载一下代码然后把index.py和Utils.py里的内容直接替换至腾讯云函数，应该就没问题了
